server:
  port: 9000
spring:
  application:
    name: client-service
  main:
     allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/clients_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  

feign:
  hystrix:
    enabled: false
        
keycloak:
  realm: formation-ms
  auth-server-url: http://localhost:8080/auth
  resource: client-app
  credentials:
    secret: 243905df-0934-49ca-9442-ca7320ae3c6b
  principal-attribute: preferred_username
  bearer-only: true
  
swagger-ui:
  client: swagger-ui
  secret: da31fa63-f172-44a1-82ae-ef77605cdfdf
---
spring:
  profiles: test
  datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: sa
        driver-class-name: org.h2.Driver
  jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate :
          ddl-auto: create

---
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1